import {
  CustomerSnapshot,
  LocationItem,
  Metric,
  PaymentInItem,
  PaymentOutItem,
  PayrollItem,
  RequestItem,
  ResourceItem,
  TimelineEvent,
} from "@/lib/types";

export const customerSnapshot: CustomerSnapshot = {
  organization: "Crush Client Group",
  primaryContact: "Lina Weber",
  email: "lina@clientgroup.example",
  phone: "+352 621 000 422",
};

export const metrics: Metric[] = [
  { label: "Active requests", value: "04" },
  { label: "Shared resources", value: "12" },
  { label: "Pending approvals", value: "02" },
  { label: "Last response time", value: "3h" },
];

export const requests: RequestItem[] = [
  {
    id: "req-1",
    subject: "Spring campaign landing page",
    category: "Project",
    priority: "High",
    status: "In Review",
    summary: "Design and content changes are being reviewed before implementation.",
  },
  {
    id: "req-2",
    subject: "Analytics access for marketing lead",
    category: "Technical",
    priority: "Medium",
    status: "Open",
    summary: "A new stakeholder needs dashboard access and monthly exports.",
  },
  {
    id: "req-3",
    subject: "April invoice clarification",
    category: "Billing",
    priority: "Low",
    status: "Waiting for Client",
    summary: "Team is waiting on confirmation for the final campaign scope split.",
  },
  {
    id: "req-4",
    subject: "Brand asset refresh",
    category: "General",
    priority: "Medium",
    status: "Closed",
    summary: "Updated exports and delivery package were shared with the client team.",
  },
];

export const resources: ResourceItem[] = [
  {
    id: "res-1",
    title: "Campaign onboarding guide",
    type: "Guide",
    summary: "Reference workflow for approvals, timelines, and deliverables.",
    updatedAt: "18 Apr 2026",
  },
  {
    id: "res-2",
    title: "Q2 performance readout",
    type: "Report",
    summary: "Snapshot of traffic, conversion, and channel-level activity.",
    updatedAt: "15 Apr 2026",
  },
  {
    id: "res-3",
    title: "Brand asset master pack",
    type: "Asset",
    summary: "Approved logos, campaign images, and social templates.",
    updatedAt: "12 Apr 2026",
  },
];

export const locations: LocationItem[] = [
  {
    id: "loc-1",
    name: "Maison du Vin",
    address: "12 Rue de la Boucherie, 1247 Luxembourg",
    city: "Luxembourg City",
    country: "Luxembourg",
    maxCapacity: 60,
    seatedCapacity: 32,
    hasOutdoorSpace: false,
    hasKitchen: false,
    hasPrivateRoom: true,
    hasSoundSystem: true,
    compatibleEventTypes: ["Wine tasting", "Speed dating", "Quiz night"],
    partnershipStage: "Active",
    primaryContact: {
      name: "Camille Hoffmann",
      role: "Manager",
      email: "camille@maisonduvin.example",
      phone: "+352 621 100 014",
    },
    accountManager: "Lina Weber",
    commercialTerms: "20% commission on bar sales above €600. Two-week exclusivity around each event.",
    partnerSince: "Feb 2025",
    lastContactDate: "02 May 2026",
    nextAction: "Confirm June wine-tasting line-up",
    nextActionDate: "15 May 2026",
    notes:
      "Strong fit for premium tastings. Camille prefers WhatsApp for last-minute updates. Avoid Tuesdays — quiet for the bar but they reserve it for staff training.",
    tags: ["Old Town", "Premium", "Indoor"],
  },
  {
    id: "loc-2",
    name: "Brasserie Belair",
    address: "48 Avenue du X Septembre, 2550 Luxembourg",
    city: "Luxembourg City",
    country: "Luxembourg",
    maxCapacity: 90,
    seatedCapacity: 70,
    hasOutdoorSpace: true,
    hasKitchen: true,
    hasPrivateRoom: true,
    hasSoundSystem: true,
    compatibleEventTypes: [
      "Cooking workshop",
      "Wine tasting",
      "Quiz night",
      "Speed dating",
    ],
    partnershipStage: "Active",
    primaryContact: {
      name: "Julien Reuter",
      role: "Owner",
      email: "julien@brasserie-belair.example",
      phone: "+352 661 222 087",
    },
    accountManager: "Lina Weber",
    commercialTerms: "Flat €350 venue fee, kitchen included. F&B minimum €15/guest.",
    partnerSince: "Sep 2024",
    lastContactDate: "28 Apr 2026",
    nextAction: "Send Q3 cooking-workshop calendar draft",
    nextActionDate: "12 May 2026",
    notes:
      "Best partner for cooking workshops thanks to the open kitchen. Chef Théo can co-host if briefed two weeks ahead.",
    tags: ["Belair", "Kitchen", "Outdoor terrace"],
  },
  {
    id: "loc-3",
    name: "Café des Artisans",
    address: "5 Place Guillaume II, 1648 Luxembourg",
    city: "Luxembourg City",
    country: "Luxembourg",
    maxCapacity: 45,
    seatedCapacity: 28,
    hasOutdoorSpace: false,
    hasKitchen: false,
    hasPrivateRoom: false,
    hasSoundSystem: true,
    compatibleEventTypes: ["Quiz night", "Speed dating"],
    partnershipStage: "Negotiating",
    primaryContact: {
      name: "Sara Klein",
      role: "Events lead",
      email: "sara@cafedesartisans.example",
      phone: "+352 621 800 312",
    },
    accountManager: "Tom Scheuer",
    commercialTerms: "Discussing 15% bar commission, no venue fee. Need agreement on cancellation policy.",
    lastContactDate: "06 May 2026",
    nextAction: "Share signed term sheet",
    nextActionDate: "13 May 2026",
    notes:
      "Central, walk-in friendly, smaller capacity. Good fit for intimate quiz nights. Sara wants the first event to be a co-branded soft launch.",
    tags: ["Old Town", "Intimate"],
  },
  {
    id: "loc-4",
    name: "Domaine Schengen",
    address: "Route du Vin 21, 5440 Remerschen",
    city: "Remerschen",
    country: "Luxembourg",
    maxCapacity: 120,
    seatedCapacity: 80,
    hasOutdoorSpace: true,
    hasKitchen: true,
    hasPrivateRoom: true,
    hasSoundSystem: false,
    compatibleEventTypes: [
      "Wine tasting",
      "Outdoor activity",
      "Cooking workshop",
    ],
    partnershipStage: "Negotiating",
    primaryContact: {
      name: "Pierre Ackermann",
      role: "Owner",
      email: "pierre@domaine-schengen.example",
      phone: "+352 691 404 001",
    },
    accountManager: "Tom Scheuer",
    commercialTerms: "Open to revenue-share on wine sales. Wants minimum 20 guests per event.",
    lastContactDate: "30 Apr 2026",
    nextAction: "Site visit + photo shoot",
    nextActionDate: "18 May 2026",
    notes:
      "Stunning vineyard setting. Pairs wine tastings with optional vineyard walk for outdoor-activity events. Limited public transport — coach hire to be priced.",
    tags: ["Moselle", "Vineyard", "Day trip"],
  },
  {
    id: "loc-5",
    name: "Rooftop Lounge Kirchberg",
    address: "Boulevard Konrad Adenauer 14, 1115 Luxembourg",
    city: "Luxembourg City",
    country: "Luxembourg",
    maxCapacity: 75,
    hasOutdoorSpace: true,
    hasKitchen: false,
    hasPrivateRoom: false,
    hasSoundSystem: true,
    compatibleEventTypes: ["Speed dating", "Quiz night"],
    partnershipStage: "Prospect",
    primaryContact: {
      name: "Anouk Steffen",
      role: "General Manager",
      email: "anouk@rooftop-kb.example",
      phone: "+352 621 553 770",
    },
    accountManager: "Lina Weber",
    lastContactDate: "04 May 2026",
    nextAction: "Send partnership deck",
    nextActionDate: "11 May 2026",
    notes:
      "Cold-introduced via Daniel at Spuerkeess. Premium clientele, weather-dependent. Worth booking a discovery call before May ends.",
    tags: ["Kirchberg", "Rooftop", "Summer"],
  },
  {
    id: "loc-6",
    name: "Forêt Aventure Esch",
    address: "Parc Galgenberg 7, 4123 Esch-sur-Alzette",
    city: "Esch-sur-Alzette",
    country: "Luxembourg",
    maxCapacity: 50,
    hasOutdoorSpace: true,
    hasKitchen: false,
    hasPrivateRoom: false,
    hasSoundSystem: false,
    compatibleEventTypes: ["Outdoor activity"],
    partnershipStage: "Prospect",
    primaryContact: {
      name: "Marc Thiel",
      role: "Operations",
      email: "marc@foret-aventure.example",
      phone: "+352 621 990 144",
    },
    accountManager: "Tom Scheuer",
    lastContactDate: "21 Apr 2026",
    nextAction: "Schedule intro call",
    notes:
      "Ropes course + team trails. Ideal for spring/summer outdoor-activity events. They've never hosted a singles-event format before — explain the flow carefully.",
    tags: ["Esch", "Outdoor only", "Spring/Summer"],
  },
  {
    id: "loc-7",
    name: "The Tap Room",
    address: "27 Rue de Strasbourg, 2561 Luxembourg",
    city: "Luxembourg City",
    country: "Luxembourg",
    maxCapacity: 55,
    seatedCapacity: 30,
    hasOutdoorSpace: false,
    hasKitchen: false,
    hasPrivateRoom: true,
    hasSoundSystem: true,
    compatibleEventTypes: ["Quiz night", "Speed dating"],
    partnershipStage: "Paused",
    primaryContact: {
      name: "Hugo Lefèvre",
      role: "Manager",
      email: "hugo@taproom.example",
      phone: "+352 621 314 805",
    },
    accountManager: "Lina Weber",
    commercialTerms: "Was 18% bar commission. To re-confirm if we resume.",
    partnerSince: "Jun 2024",
    lastContactDate: "08 Mar 2026",
    nextAction: "Re-engage in September after their renovation",
    nextActionDate: "05 Sep 2026",
    notes:
      "Closed for renovation through August. Hugo wants to restart with a quiz-night relaunch event. Good audience overlap, just put on hold.",
    tags: ["Gare", "Casual", "On hold"],
  },
  {
    id: "loc-8",
    name: "Beim Bouneschlupp",
    address: "3 Rue du Marché-aux-Herbes, 1728 Luxembourg",
    city: "Luxembourg City",
    country: "Luxembourg",
    maxCapacity: 40,
    seatedCapacity: 36,
    hasOutdoorSpace: false,
    hasKitchen: true,
    hasPrivateRoom: false,
    hasSoundSystem: false,
    compatibleEventTypes: ["Cooking workshop"],
    partnershipStage: "Archived",
    primaryContact: {
      name: "Renée Mertens",
      role: "Owner",
      email: "renee@bouneschlupp.example",
      phone: "+352 621 477 002",
    },
    accountManager: "Lina Weber",
    lastContactDate: "12 Feb 2026",
    notes:
      "Tried two cooking workshops in late 2025 — kitchen too small for 12 guests, owner uncomfortable with non-restaurant programming. Closed loop politely.",
    tags: ["Old Town", "Tried in 2025"],
  },
];

export const timeline: TimelineEvent[] = [
  {
    id: "evt-1",
    date: "21 Apr",
    title: "Support request updated",
    description: "The landing page change request moved into review with the design team.",
  },
  {
    id: "evt-2",
    date: "19 Apr",
    title: "Resource uploaded",
    description: "The Q2 readout deck was added to the shared resource center.",
  },
  {
    id: "evt-3",
    date: "16 Apr",
    title: "Account note added",
    description: "Primary contact preferences were refreshed for campaign approvals.",
  },
];

export const paymentsIn: PaymentInItem[] = [
  {
    id: "pin-1",
    date: "2026-04-12",
    amount: 1280,
    source: "Wine tasting tickets — Maison du Vin",
    clientName: "Lot de 32 billets",
    status: "Paid",
    reference: "INV-2026-041",
  },
  {
    id: "pin-2",
    date: "2026-04-26",
    amount: 950,
    source: "Cooking workshop — Brasserie Belair",
    clientName: "Groupe corporate Spuerkeess",
    status: "Paid",
    reference: "INV-2026-044",
  },
  {
    id: "pin-3",
    date: "2026-05-08",
    amount: 420,
    source: "Quiz night tickets — Café des Artisans",
    status: "Overdue",
    reference: "INV-2026-049",
  },
  {
    id: "pin-4",
    date: "2026-05-20",
    amount: 1680,
    source: "Speed dating — Maison du Vin",
    clientName: "Vente en ligne",
    status: "Pending",
    reference: "INV-2026-052",
  },
  {
    id: "pin-5",
    date: "2026-05-28",
    amount: 2100,
    source: "Wine tasting — Domaine Schengen",
    clientName: "Groupe ArcelorMittal",
    status: "Scheduled",
    reference: "INV-2026-055",
  },
  {
    id: "pin-6",
    date: "2026-06-04",
    amount: 780,
    source: "Quiz night tickets — Brasserie Belair",
    status: "Scheduled",
    reference: "INV-2026-058",
  },
  {
    id: "pin-7",
    date: "2026-06-15",
    amount: 1450,
    source: "Cooking workshop — Brasserie Belair",
    clientName: "Team-building Deloitte",
    status: "Pending",
    reference: "INV-2026-061",
  },
];

export const paymentsOut: PaymentOutItem[] = [
  {
    id: "pout-1",
    date: "2026-04-15",
    amount: 240,
    locationId: "loc-1",
    payee: "Maison du Vin",
    description: "20% commission bar — wine tasting avril",
    status: "Paid",
  },
  {
    id: "pout-2",
    date: "2026-04-28",
    amount: 350,
    locationId: "loc-2",
    payee: "Brasserie Belair",
    description: "Frais de salle forfaitaires — cooking workshop",
    status: "Paid",
  },
  {
    id: "pout-3",
    date: "2026-05-10",
    amount: 180,
    payee: "Imprimerie Wagner",
    description: "Impression flyers — campagne mai",
    status: "Overdue",
  },
  {
    id: "pout-4",
    date: "2026-05-22",
    amount: 336,
    locationId: "loc-1",
    payee: "Maison du Vin",
    description: "20% commission bar — speed dating",
    status: "Pending",
  },
  {
    id: "pout-5",
    date: "2026-05-30",
    amount: 420,
    locationId: "loc-4",
    payee: "Domaine Schengen",
    description: "Revenue share — wine tasting groupe",
    status: "Scheduled",
  },
  {
    id: "pout-6",
    date: "2026-06-05",
    amount: 350,
    locationId: "loc-2",
    payee: "Brasserie Belair",
    description: "Frais de salle — quiz night",
    status: "Scheduled",
  },
  {
    id: "pout-7",
    date: "2026-06-12",
    amount: 95,
    payee: "Canva Pro",
    description: "Abonnement design — juin",
    status: "Scheduled",
  },
];

export const payroll: PayrollItem[] = [
  {
    id: "pay-1",
    date: "2026-04-30",
    amount: 3200,
    employeeName: "Lina Weber",
    category: "Salary",
    description: "Salaire avril 2026",
    status: "Paid",
  },
  {
    id: "pay-2",
    date: "2026-04-30",
    amount: 2950,
    employeeName: "Tom Scheuer",
    category: "Salary",
    description: "Salaire avril 2026",
    status: "Paid",
  },
  {
    id: "pay-3",
    date: "2026-05-06",
    amount: 78,
    employeeName: "Tom Scheuer",
    category: "Expense",
    description: "Taxi visite Domaine Schengen",
    status: "Pending",
  },
  {
    id: "pay-4",
    date: "2026-05-14",
    amount: 142,
    employeeName: "Lina Weber",
    category: "Expense",
    description: "Dîner client — Brasserie Belair",
    status: "Pending",
  },
  {
    id: "pay-5",
    date: "2026-05-31",
    amount: 3200,
    employeeName: "Lina Weber",
    category: "Salary",
    description: "Salaire mai 2026",
    status: "Scheduled",
  },
  {
    id: "pay-6",
    date: "2026-05-31",
    amount: 2950,
    employeeName: "Tom Scheuer",
    category: "Salary",
    description: "Salaire mai 2026",
    status: "Scheduled",
  },
  {
    id: "pay-7",
    date: "2026-06-15",
    amount: 500,
    employeeName: "Lina Weber",
    category: "Bonus",
    description: "Bonus Q2 — objectifs partenariats",
    status: "Scheduled",
  },
];
